# Generated by Django 6.0.4 on 2026-04-20 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_id', models.CharField(help_text='ID numérico único asignado por Facebook', max_length=100, unique=True)),
                ('access_token', models.TextField(help_text='Token OAuth para autenticar peticiones a Facebook API')),
                ('nombre', models.CharField(help_text='Nombre completo del usuario en Facebook', max_length=200)),
                ('email', models.EmailField(blank=True, help_text='Correo electrónico del usuario (si autorizó compartirlo)', max_length=254)),
                ('foto_perfil', models.URLField(blank=True, help_text='URL de la foto de perfil de Facebook')),
                ('fecha_vinculacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se vinculó la cuenta')),
                ('user', models.OneToOneField(help_text='Usuario Django vinculado a esta cuenta Facebook', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuenta de Facebook',
                'verbose_name_plural': 'Cuentas de Facebook',
                'ordering': ['-fecha_vinculacion'],
            },
        ),
        migrations.CreateModel(
            name='FacebookPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(help_text='Texto del post publicado en Facebook')),
                ('post_id', models.CharField(blank=True, help_text='ID único del post asignado por Facebook (formato: user_id_post_id)', max_length=200)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se publicó el post')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Última vez que se actualizaron las métricas')),
                ('likes', models.IntegerField(default=0, help_text="Cantidad de 'Me gusta' del post")),
                ('comentarios', models.IntegerField(default=0, help_text='Cantidad de comentarios del post')),
                ('compartidos', models.IntegerField(default=0, help_text='Cantidad de veces que se compartió el post')),
                ('alcance', models.IntegerField(default=0, help_text='Número de personas únicas que vieron el post')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado'), ('eliminado', 'Eliminado'), ('error', 'Error al publicar')], default='publicado', help_text='Estado actual de la publicación', max_length=20)),
                ('account', models.ForeignKey(help_text='Cuenta de Facebook que realizó la publicación', on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='social_app.facebookaccount')),
            ],
            options={
                'verbose_name': 'Publicación de Facebook',
                'verbose_name_plural': 'Publicaciones de Facebook',
                'ordering': ['-fecha_publicacion'],
                'indexes': [models.Index(fields=['-fecha_publicacion'], name='social_app__fecha_p_768bf5_idx'), models.Index(fields=['post_id'], name='social_app__post_id_5fce18_idx')],
            },
        ),
    ]
