# Generated by Django 5.2.11 on 2026-04-20 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpost',
            name='page_access_token',
            field=models.TextField(blank=True, help_text='Token de acceso de la página usado al publicar'),
        ),
    ]
