"""
Django settings for facebook_integration project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+nr5byc$rk_l9*sohm4ctw&6w*qr=%2hg1osm$#)3=d=dp=mf1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['examenu3felixmedina.pythonanywhere.com', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    # Aplicaciones integradas de Django:
    'django.contrib.admin',          # Panel de administración
    'django.contrib.auth',           # Sistema de autenticación
    'django.contrib.contenttypes',   # Gestión de tipos de contenido
    'django.contrib.sessions',       # Manejo de sesiones
    'django.contrib.messages',       # Sistema de mensajes
    'django.contrib.staticfiles',    # Archivos estáticos (CSS, JS, imágenes)
    
    # Aplicaciones de terceros:
    'rest_framework',                # Django REST Framework (para APIs)
    'corsheaders',                   # Manejo de CORS para peticiones externas
    
    # Nuestra aplicación personalizada:
    'social_app',                    # App que creamos para Facebook
]


# MIDDLEWARE (procesadores de peticiones)
# Asegúrate de que CorsMiddleware esté ANTES de CommonMiddleware
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # ← Agregar CORS
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
# CONFIGURACIÓN DE CORS (permitir peticiones desde otros dominios)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]

ROOT_URLCONF = 'facebook_integration.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'facebook_integration.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        # Motor de base de datos (MySQL)
        'ENGINE': 'django.db.backends.mysql',
        
        # Nombre de la base de datos que creamos
        'NAME': 'examenu3Felixmed$facebook',
        
        # Usuario de MySQL
        'USER': 'examenu3Felixmed',
        
        # Contraseña de MySQL
        'PASSWORD': 'medina1x',
        
        # Servidor PythonAnywhere
        'HOST': 'examenu3Felixmedina.mysql.pythonanywhere-services.com',
        
        # Puerto por defecto de MySQL
        'PORT': '3306',
        
        # Opciones adicionales para el conector
        'OPTIONS': {
            'charset': 'utf8mb4',  # Soporte completo de Unicode
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",  # Validación estricta
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# CONFIGURACIÓN DE ZONA HORARIA
TIME_ZONE = 'America/Hermosillo'  # Ajusta a tu zona horaria
USE_TZ = True

# CONFIGURACIÓN DE IDIOMA
LANGUAGE_CODE = 'es-mx'  # Español de México

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = '/home/examenu3Felixmedina/felixmedinafacebook/facebook_integration/staticfiles/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# CONFIGURACIÓN DE FACEBOOK
# Aquí pondremos las credenciales que obtuvimos de Facebook Developers
FACEBOOK_APP_ID = '2067776030644149'
FACEBOOK_APP_SECRET = '98a2b6c55f9fcecb5d098db0f9206c86'
FACEBOOK_REDIRECT_URI = 'https://examenu3felixmedina.pythonanywhere.com/facebook/callback/'